name: meals_recipes
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  envied: ^0.5.4+1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  dots_indicator: ^3.0.0
  flutter_screenutil: ^5.9.3
  animated_text_kit: ^4.2.2
  fluttertoast: ^8.2.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ui/

flutter_gen:
  output: lib/ui/widgets/generated
  line_length: 80
  integration:
    flutter_svg: true
